### ISSUE TITLE
Change the size of the canvas dynamically based on screen resolution. 

### ISSUE THREAD

**Issue by murtazabasu** [andfanilo/streamlit-drawable-canvas#59] opened 2021-09-08 10:42 UTC
Hello,

Is it possible to adjust the size of the canvas based on screen resolution (something like viewport in html)?

When I run the application on my laptop, the canvas looks pretty normal. But when I try to use it on an ipad or mobile, the canvas looks enlarged and its not so convenient to use it. It would be really great if the canvas could adjust automatically to screens of different resolutions.

**Comment by andfanilo** [comment] 2021-09-08 18:02
Hello @murtazabasu ,

Not yet possible and a dupe of #39 :) I'll have to get back to it sometime this month. Hope you don't mind if I close this in favor for the original one!

Have a nice day,
Fanilo

**Closed by andfanilo** 2021-09-08 18:02 UTC
