### ISSUE TITLE
background image on cloud

### ISSUE THREAD

**Issue by RRaphaell** [andfanilo/streamlit-drawable-canvas#80] opened 2022-07-15 15:09 UTC
I can add a background image to canvas locally, but it does not appear on the cloud

I'm using:
streamlit==1.10.0
streamlit-drawable-canvas==0.9.0

**Comment by RRaphaell** [comment] 2022-07-15 15:12
It doesn't work on [basic example](https://share.streamlit.io/andfanilo/streamlit-drawable-canvas-demo/app.py) either, I can't add a background image

**Comment by andfanilo** [comment] 2022-07-15 16:55
Hello,
Yes, this is a duplicate of #70, it broke since v0.9.0, you can downgrade to 0.8.0 for now until it's fixed. 
I will close this as duplicate if you don't mind

**Closed by andfanilo** 2022-07-15 16:55 UTC
